services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: planner_api_db
    ports:
      - "3306:3306"
    # volumes:
    #   - mysql_data:/var/lib/mysql
    networks:
      - my_network

# volumes:
#   mysql_data:
networks:
  my_network:
    driver: bridge
